# Generated by Django 4.2.25 on 2025-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_de", models.CharField(max_length=160)),
                ("title_en", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("client", models.CharField(blank=True, max_length=160)),
                ("summary_de", models.TextField()),
                ("summary_en", models.TextField()),
                ("content_de", models.TextField(blank=True)),
                ("content_en", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("cover", models.ImageField(blank=True, null=True, upload_to="cases/")),
                ("published", models.BooleanField(default=True)),
            ],
            options={"ordering": ["-date"],},
        ),
    ]
