# Generated by Django 4.2.25 on 2025-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casestudy", old_name="cover", new_name="image",
        ),
        migrations.RenameField(
            model_name="casestudy", old_name="content_de", new_name="summary",
        ),
        migrations.RenameField(
            model_name="casestudy", old_name="title_de", new_name="title",
        ),
        migrations.RemoveField(model_name="casestudy", name="client",),
        migrations.RemoveField(model_name="casestudy", name="content_en",),
        migrations.RemoveField(model_name="casestudy", name="summary_de",),
        migrations.RemoveField(model_name="casestudy", name="summary_en",),
        migrations.RemoveField(model_name="casestudy", name="title_en",),
        migrations.AddField(
            model_name="casestudy",
            name="category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
