# Generated by Django 4.2.25 on 2025-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_cover_casestudy_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "language",
                    models.CharField(
                        default="de", max_length=5, verbose_name="Language"
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(default=False, verbose_name="Processed"),
                ),
            ],
            options={
                "verbose_name": "Contact message",
                "verbose_name_plural": "Contact messages",
                "ordering": ["-created"],
            },
        ),
    ]
