# Generated by Django 4.2.25 on 2025-11-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactmessage", name="name",),
        migrations.AddField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Company"
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="first_name",
            field=models.CharField(default=1, max_length=80, verbose_name="First name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="last_name",
            field=models.CharField(default="", max_length=80, verbose_name="Last name"),
            preserve_default=False,
        ),
    ]
