# Generated by Django 4.2.25 on 2025-11-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_remove_contactmessage_name_contactmessage_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("title_de", models.CharField(max_length=160)),
                ("title_en", models.CharField(max_length=160)),
                ("body_de", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="casestudy",
            name="kpis",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste von KPIs (als Text)",
                verbose_name="KPIs",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="z. B. Snowflake, DBT, Airflow, Django",
                max_length=220,
                verbose_name="Technologie-Stack",
            ),
        ),
    ]
