# Generated by Django 4.2.25 on 2025-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_page_casestudy_kpis_casestudy_tech_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="client_brief",
            field=models.TextField(
                blank=True,
                help_text="Kurzbeschreibung des Kunden (keine Namen).",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="problem_brief",
            field=models.TextField(
                blank=True,
                help_text="Welches Problem/Engpass bestand?",
                verbose_name="Problem",
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="result_points",
            field=models.TextField(
                blank=True,
                help_text="Eine Aufzählung, je Zeile ein Punkt.",
                verbose_name="Result (Bullet points)",
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="kpis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="tech_stack",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
