# Generated by Django 4.2.5 on 2025-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_casestudy_client_brief_casestudy_problem_brief_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Steuert, ob diese Case Study auf der Website angezeigt wird.",
                verbose_name="Aktiv",
            ),
        ),
    ]
