# Generated by Django 4.2.5 on 2026-01-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_casestudy_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='First name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('branches', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branches')),
                ('pains', models.CharField(blank=True, max_length=255, null=True, verbose_name='Challenges')),
                ('start_mode', models.CharField(blank=True, max_length=80, null=True, verbose_name='Start mode')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('language', models.CharField(default='de', max_length=5, verbose_name='Language')),
                ('handled', models.BooleanField(default=False, verbose_name='Processed')),
            ],
            options={
                'verbose_name': 'Start request',
                'verbose_name_plural': 'Start requests',
                'ordering': ['-created'],
            },
        ),
    ]
