# Generated by Django 4.2.5 on 2026-01-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_startrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
