# Generated by Django 4.2.5 on 2026-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_casestudy_preview_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='problem_brief_en',
            field=models.TextField(blank=True, help_text='English version of the challenge description.', verbose_name='Problem (EN)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='result_points_en',
            field=models.TextField(blank=True, help_text='English bullet points, one per line.', verbose_name='Result Bullet points (EN)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='summary_en',
            field=models.TextField(blank=True, help_text='English version of the solution text.', verbose_name='Solution (EN)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='problem_brief',
            field=models.TextField(blank=True, help_text='Deutsche Version: Welches Problem/Engpass bestand?', verbose_name='Problem (DE)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='result_points',
            field=models.TextField(blank=True, help_text='Deutsche Aufzählung, je Zeile ein Punkt.', verbose_name='Result Bullet points (DE)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='summary',
            field=models.TextField(blank=True, help_text='Deutsche Version des Lösungstexts.', verbose_name='Solution (DE)'),
        ),
    ]
