# Generated by Django 4.2.5 on 2026-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_set_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, help_text='Auswahl aus dem Kontaktformular.', max_length=60, verbose_name='Requested service'),
        ),
    ]
